# Generated by Django 3.0.8 on 2020-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TodoText', models.CharField(max_length=200)),
                ('Added_date', models.DateTimeField(auto_now=True)),
                ('Update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
